-- Ensure all single-column numeric PKs in public schema are IDENTITY and sequences aligned safely
DO $$
DECLARE
  r RECORD;
  max_val bigint;
  restart_val bigint;
BEGIN
  -- 1) Convert non-IDENTITY PKs to GENERATED BY DEFAULT AS IDENTITY
  FOR r IN (
    SELECT 
      n.nspname AS schema_name,
      c.relname AS table_name,
      a.attname AS column_name
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = con.conkey[1]
    JOIN pg_type t ON t.oid = a.atttypid
    WHERE con.contype = 'p'                 -- primary key
      AND n.nspname = 'public'              -- only public schema
      AND cardinality(con.conkey) = 1       -- single-column PK only
      AND t.typname IN ('int2','int4','int8')  -- smallint, integer, bigint
      AND a.attidentity = ''                -- not identity yet
  ) LOOP
    RAISE NOTICE 'Converting %.% column % to GENERATED BY DEFAULT AS IDENTITY', 
      r.schema_name, r.table_name, r.column_name;

    -- Drop any existing default to allow adding IDENTITY
    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %I DROP DEFAULT',
      r.schema_name, r.table_name, r.column_name);

    -- Add IDENTITY (BY DEFAULT to allow manual inserts when needed)
    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
      r.schema_name, r.table_name, r.column_name);

    -- Compute restart value from existing data
    EXECUTE format('SELECT COALESCE(MAX(%I), 0)::bigint FROM %I.%I',
      r.column_name, r.schema_name, r.table_name)
      INTO max_val;

    IF max_val IS NULL OR max_val < 1 THEN
      restart_val := 1;  -- empty table -> next value should be 1
    ELSE
      restart_val := max_val + 1; -- continue after current max
    END IF;

    -- Align the identity to the proper next value
    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %I RESTART WITH %s',
      r.schema_name, r.table_name, r.column_name, restart_val::text);
  END LOOP;

  -- 2) For PKs that are already IDENTITY, just align their next values safely
  FOR r IN (
    SELECT 
      n.nspname AS schema_name,
      c.relname AS table_name,
      a.attname AS column_name
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = con.conkey[1]
    JOIN pg_type t ON t.oid = a.atttypid
    WHERE con.contype = 'p'
      AND n.nspname = 'public'
      AND cardinality(con.conkey) = 1
      AND t.typname IN ('int2','int4','int8')
      AND a.attidentity <> ''              -- already identity
  ) LOOP
    EXECUTE format('SELECT COALESCE(MAX(%I), 0)::bigint FROM %I.%I',
      r.column_name, r.schema_name, r.table_name)
      INTO max_val;

    IF max_val IS NULL OR max_val < 1 THEN
      restart_val := 1;
    ELSE
      restart_val := max_val + 1;
    END IF;

    RAISE NOTICE 'Aligning identity for %.% column % -> RESTART WITH %',
      r.schema_name, r.table_name, r.column_name, restart_val;

    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %I RESTART WITH %s',
      r.schema_name, r.table_name, r.column_name, restart_val::text);
  END LOOP;
END
$$;
